language: go
go:
      - 1.5.2

before_install:
      - sudo apt-get update -qq
      - sudo apt-get install -qq libgdal-dev
      - curl -ks 'https://gist.github.com/nicerobot/5160658/raw/install-gdalpc.sh' | sudo bash -
      - go get github.com/axw/gocov/gocov
      - go get github.com/mattn/goveralls
      - go get golang.org/x/tools/cmd/cover

install:
      - go get -d -t ./...

script:
      - go test ./...
      - bash ./.travis/test-coverage.sh
