language: go
go:
- 1.5.2
- 1.6.2
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- wget https://github.com/spatialmodel/inmap/releases/download/v1.1.0/testdata_v1.1.0.zip
- unzip testdata_v1.1.0.zip

install:
- go get -d -t ./...
script:
- go test ./...
- bash ./.travis/test_coverage.sh

env:
- COVERALLS_TOKEN = GVQhuqfj8QpDFM6zqabD9OFOCrR5eEeAb
