language: go
go:
- 1.6.2
- 1.7rc4

before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- wget https://github.com/spatialmodel/inmap/releases/download/v1.1.0/testdata_v1.2.0-dev.zip
- unzip testdata_v1.2.0-dev.zip

install:
- go get -d -t ./...
script:
- go test -short ./...
- bash ./.travis/test_coverage.sh

env:
  global:
    - COVERALLS_TOKEN=rK3QSbCh7y0Tdfu4K0arUQSJqHJCl4ebP
