language: go
go:
- 1.7.5
- 1.8

before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- go get github.com/kardianos/govendor

install:
- govendor sync
script:
- go test -short ./...
- bash ./.travis/test_coverage.sh

env:
  global:
    - COVERALLS_TOKEN=rK3QSbCh7y0Tdfu4K0arUQSJqHJCl4ebP
