language: go
go:
      - 1.5.2

before_install:
      - go get github.com/axw/gocov/gocov
      - go get github.com/mattn/goveralls
      - go get golang.org/x/tools/cmd/cover
      - go get github.com/github/git-lfs
      - git lfs install
      - git lfs init
      - git lfs pull

install:
      - go get -d -t ./...

script:
      - go test ./...
      - bash ./.travis/test-coverage.sh
