

InMAPData = "${inmapData}"

EmissionsShapefiles = [
	#"${nei2005BioFireEmissions}",
	#"${nei2005ElevatedEmissions}",
	"${nei2005GroundLevelEmissions}"
]
EmissionUnits = "tons/year"

OutputFile = "nei2005/2005nei_output.shp"

OutputVariables = [
	"NH3",
	"NOx",
	"Primary PM2.5",
	"SOA",
	"SOx",
	"Total PM2.5",
	"VOC",
	"pNH4",
	"pNO3",
	"pSO4"
]


HTTPAddress = ":8080"

[VarGrid]

# VariableGridXo and VariableGridYo are the X and Y coordinates of the
# lower-left corner of the InMAP grid.
VariableGridXo= -2736000.0
VariableGridYo= -2088000.0

# VariableGridDx and VariableGridDy are the X and Y edge lengths of grid
# cells in the outermost nest, in meters.
VariableGridDx= 48000.0
VariableGridDy= 48000.0

# Xnests and Ynests specify nesting multiples in the X and Y directions.
# For instance, if Xnests and Ynests are both [100, 2, 2, 2] and
# VariableGridDy and VariableGridDx are both 40000, the outermost
# nest would have 100 grid cells in each direction with 40 km resolution,
# and there would be three levels of inner nesting, each at double the
# resolution of the previous nest, with the innermost nest having a grid
# cell length of 5 km.
Xnests= [111, 2, 2, 3, 2, 2]
Ynests= [84, 2, 2, 3, 2, 2]

# HiResLayers is the number of layers, starting at ground level, to do
# nesting in. Layers above this will have all grid cells in the lowest
# spatial resolution.
HiResLayers= 8

# GridProj gives projection info for the CTM grid in Proj4 or WKT format.
GridProj= "+proj=lcc +lat_1=33.000000 +lat_2=45.000000 +lat_0=40.000000 +lon_0=-97.000000 +x_0=0 +y_0=0 +a=6370997.000000 +b=6370997.000000 +to_meter=1"

# PopDensityCutoff is a limit for people per unit area in a grid cell
# (units will typically be either people / m^2 or people / degree^2,
# depending on the spatial projection of the model grid). If
# the population density in a grid cell is above this level, the cell in question
# is a candidate for splitting into smaller cells.
PopDensityCutoff= 0.0055

# PopCutoff is a limit for the total number of people in a grid cell.
# If the total population in a grid cell is above this level, the cell in question
# is a candidate for splitting into smaller cells.
PopCutoff= 40000.0

PopConcThreshold= 0.000001

# CensusFile is the path to the shapefile holding population information.
CensusFile= "${censusFile}"

# CensusPopColumns is a list of the data fields in CensusFile that should
# be included as population estimates in the model. They can be population
# of different demographics or for different population scenarios.
CensusPopColumns= ["TotalPop", "WhiteNoLat", "Black", "Native", "Asian", "Latino"]

# PopGridColumn is the name of the field in CensusFile that contains the data
# that should be compared to PopCutoff and PopDensityCutoff when determining
# if a grid cell should be split. It should typically be one of the fields
# in CensusPopColumns.
PopGridColumn= "TotalPop"

# MortalityRateFile is the path to the shapefile containing baseline
# mortality rate data.
MortalityRateFile= "${mortalityRateFile}"

# MortalityRateColumn is the name of the field in MortalityRateFile that
# contains the baseline mortality rate data, in units of deaths per year
# per 100,000 people.
MortalityRateColumn= "AllCause"
