InMAPData = "../testdata/inmapData.ncf"
EmissionsShapefiles = [
	"../testdata/testEmis.shp"
]
OutputTemplate = "../testdata/output_[layer].shp"
HTTPport = "8080"

[VarGrid]
VariableGridXo= -2004000.0
VariableGridYo= -540000.0
VariableGridDx= 12000.0
VariableGridDy= 12000.0
Xnests= [12, 2, 2]
Ynests= [10, 2, 2]
HiResLayers= 8
CtmGridXo= -2004000.0
CtmGridYo= -540000.0
CtmGridDx= 12000.0
CtmGridDy= 12000.0
CtmGridNx= 24
CtmGridNy= 20
GridProj= "+proj=lcc +lat_1=33.000000 +lat_2=45.000000 +lat_0=40.000000 +lon_0=-97.000000 +x_0=0 +y_0=0 +a=6370997.000000 +b=6370997.000000 +to_meter=1"
PopDensityCutoff= 0.001
PopCutoff= 25000.0
BboxOffset= 1.0
CensusFile= "../testdata/census2012.shp"
CensusPopColumns= ["TotalPop", "WhiteNoLat", "Black", "Native", "Asian", "Latino"]
PopGridColumn= "TotalPop"
MortalityRateFile= "../testdata/MortalityRate.shp"
MortalityRateColumn= "AllCause"
