InMAPData = "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/testInMAPInputData.ncf"

VariableGridData = "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/inmapVarGrid.gob"

EmissionsShapefiles = [
	"${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/testEmis.shp"
]
EmissionUnits = "tons/year"

OutputFile = "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/output_${InMAPRunType}.shp"
OutputVariables = [
  "TotalPop deaths",
	"WhiteNoLat deaths",
	"Black deaths",
	"Native deaths",
	"Asian deaths",
	"Latino deaths",
  "TotalPop",
	"Total PM2.5",
	"PM2.5 emissions",
	"Baseline Total PM2.5",
	"WindSpeed"
]

HTTPport = "8080"

SROutputFile = "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/testSR.ncf"

[VarGrid]
VariableGridXo= -4000.0
VariableGridYo= -4000.0
VariableGridDx= 4000.0
VariableGridDy= 4000.0
Xnests= [2, 2, 2]
Ynests= [2, 2, 2]
HiResLayers= 1
GridProj= "+proj=lcc +lat_1=33.000000 +lat_2=45.000000 +lat_0=40.000000 +lon_0=-97.000000 +x_0=0 +y_0=0 +a=6370997.000000 +b=6370997.000000 +to_meter=1"
PopDensityThreshold= 0.001
PopThreshold= 25000.0
PopConcThreshold= 0.000001
CensusFile= "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/testPopulation.shp"
CensusPopColumns= ["TotalPop", "WhiteNoLat", "Black", "Native", "Asian", "Latino"]
PopGridColumn= "TotalPop"
MortalityRateFile= "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/testMortalityRate.shp"
MortalityRateColumn= "AllCause"
